//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CADASTRO_ENDERECOS
    {
        public int COD_CADASTRO { get; set; }
        public string DESC_CADPRO { get; set; }
        public string DESC_ENDERECO { get; set; }
        public Nullable<int> COD_CIDADE { get; set; }
        public string DESC_CIDADE { get; set; }
        public string COD_ESTADO { get; set; }
        public string DESC_BAIRRO { get; set; }
        public Nullable<int> NUM_CAIXA_POSTAL { get; set; }
        public string DESC_CEP { get; set; }
        public Nullable<int> COD_PAIS { get; set; }
        public string DESC_DISTRITO { get; set; }
        public string DESC_E_MAIL_COMERCIAL { get; set; }
        public string DESC_E_MAIL_FINANCEIRO { get; set; }
    
        public virtual TB_CADASTRO TB_CADASTRO { get; set; }
    }
}
