//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CLASSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CLASSE()
        {
            this.TB_PRODUTO = new HashSet<TB_PRODUTO>();
        }
    
        public int COD_CLASSE { get; set; }
        public string DESC_CLASSE { get; set; }
        public Nullable<decimal> PERC_COMISSAO1 { get; set; }
        public Nullable<decimal> PERC_COMISSAO2 { get; set; }
        public short NUM_CLASSE { get; set; }
        public short NUM_SUBCLASSE { get; set; }
        public Nullable<decimal> PERC_CUSTO { get; set; }
        public Nullable<decimal> VAL_CUSTO { get; set; }
        public Nullable<int> COD_RAMO { get; set; }
        public string IND_TIPO { get; set; }
        public Nullable<int> COD_LOTE_TIPO { get; set; }
        public Nullable<int> COD_MENSAGEM { get; set; }
        public string IND_AREA { get; set; }
        public string IND_SITUACAO { get; set; }
        public Nullable<decimal> PERC_MARGEM_VAREJO { get; set; }
        public Nullable<decimal> PERC_MARGEM_ATACADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PRODUTO> TB_PRODUTO { get; set; }
    }
}
