//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CADASTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CADASTRO()
        {
            this.TB_CADASTRO_ENDERECOS = new HashSet<TB_CADASTRO_ENDERECOS>();
            this.TB_FILIAL = new HashSet<TB_FILIAL>();
            this.TB_FILIAL1 = new HashSet<TB_FILIAL>();
            this.TB_LOTE_TIPO = new HashSet<TB_LOTE_TIPO>();
            this.TB_PROPRIEDADE = new HashSet<TB_PROPRIEDADE>();
            this.TB_PEDIDO_CAB = new HashSet<TB_PEDIDO_CAB>();
            this.TB_PEDIDO_CAB1 = new HashSet<TB_PEDIDO_CAB>();
        }
    
        public int COD_CADASTRO { get; set; }
        public Nullable<int> COD_MOTIVO { get; set; }
        public int COD_TIPO_CADASTRO { get; set; }
        public Nullable<int> COD_REGIAO { get; set; }
        public Nullable<int> COD_PAIS { get; set; }
        public Nullable<int> COD_ESTADO_CIVIL { get; set; }
        public Nullable<int> COD_RAMO { get; set; }
        public string COD_ESTADO { get; set; }
        public string NOME { get; set; }
        public string DESC_ENDERECO { get; set; }
        public string DESC_CIDADE { get; set; }
        public string DESC_CEP { get; set; }
        public string NUM_CGC_CPF { get; set; }
        public string NUM_INSCRICAO { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
        public string IND_SEXO_CATEGORIA { get; set; }
        public Nullable<int> NUM_CAIXA_POSTAL { get; set; }
        public Nullable<System.DateTime> DT_CANCELAMENTO { get; set; }
        public string DESC_TELEFONE { get; set; }
        public string DESC_CELULAR { get; set; }
        public string NOME_CONTATO { get; set; }
        public Nullable<System.DateTime> DT_NASCIMENTO { get; set; }
        public string DESC_BAIRRO { get; set; }
        public Nullable<decimal> PERC_FUNRURAL { get; set; }
        public Nullable<decimal> VAL_LIMITE { get; set; }
        public string DESC_FANTASIA { get; set; }
        public string DESC_CIDADE_COBRANCA { get; set; }
        public string DESC_ENDERECO_COBRANCA { get; set; }
        public string DESC_ESTADO_COBRANCA { get; set; }
        public string DESC_CEP_COBRANCA { get; set; }
        public string DESC_TELEFONE_COMERCIAL { get; set; }
        public Nullable<int> NUM_JUNTA { get; set; }
        public Nullable<System.DateTime> DT_FUNDACAO { get; set; }
        public Nullable<System.DateTime> DT_JUNTA { get; set; }
        public string DESC_FAX { get; set; }
        public string NOME_MAE { get; set; }
        public string NOME_PAI { get; set; }
        public string DESC_NATURALIDADE { get; set; }
        public string DESC_ESTADO_NATURAL { get; set; }
        public Nullable<System.DateTime> DT_EXPEDICAO_IDENTIDADE { get; set; }
        public string DESC_E_MAIL { get; set; }
        public string DESC_FAX_COBRANCA { get; set; }
        public string IND_SEPROC_SIMNAO { get; set; }
        public string DESC_INSCRICAO_MUNICIPAL { get; set; }
        public string NOME_CONJUGE { get; set; }
        public string DESC_CPF_CONJUGE { get; set; }
        public string DESC_IDENTIDADE_CONJUGE { get; set; }
        public Nullable<int> COD_CLASS_CADASTRO { get; set; }
        public Nullable<int> COD_BANCO_AGENCIA { get; set; }
        public Nullable<int> COD_OPERACAO_CC { get; set; }
        public Nullable<System.DateTime> DT_NASCIMENTO_CONTATO { get; set; }
        public string NOME_CONTATO2 { get; set; }
        public Nullable<System.DateTime> DT_NASCIMENTO2 { get; set; }
        public Nullable<int> COD_VENDEDOR { get; set; }
        public Nullable<decimal> PERC_COMISSAO { get; set; }
        public string DESC_COMPLEMENTO { get; set; }
        public string IND_FISICA_JURIDICA { get; set; }
        public string DESC_ENDERECO_ENTREGA { get; set; }
        public string DESC_CIDADE_ENTREGA { get; set; }
        public string DESC_BAIRRO_ENTREGA { get; set; }
        public string DESC_OBS { get; set; }
        public string DESC_OBS1 { get; set; }
        public string DESC_OBS2 { get; set; }
        public string DESC_FORMA_COMPRA { get; set; }
        public Nullable<int> COD_USUARIO { get; set; }
        public string DESC_REF_COMERCIAL1 { get; set; }
        public string DESC_REF_COMERCIAL2 { get; set; }
        public string DESC_REF_COMERCIAL3 { get; set; }
        public string DESC_REF_BANCO1 { get; set; }
        public string DESC_REF_BANCO2 { get; set; }
        public string DESC_REF_BANCO3 { get; set; }
        public string DESC_REF_PARENTE_NOME { get; set; }
        public string DESC_REF_PARENTE_ENDERECO { get; set; }
        public string DESC_REF_PARENTE_CIDADE { get; set; }
        public string DESC_REF_PARENTE_TELEFONE { get; set; }
        public string DESC_REF_OUTRAS { get; set; }
        public Nullable<int> COD_CADASTRO_NOVO { get; set; }
        public string DESC_ORGAO_EMISSOR { get; set; }
        public string DESC_INSCRICAO_INSS { get; set; }
        public string DESC_CARTEIRA { get; set; }
        public Nullable<System.DateTime> DT_EXPEDICAO_CARTEIRA { get; set; }
        public Nullable<int> COD_VENDEDOR_PREPOSTO { get; set; }
        public Nullable<int> COD_CIDADE { get; set; }
        public string IND_LIBERA_VENDA { get; set; }
        public string IND_REGIME_ESPECIAL { get; set; }
        public string DESC_HOBBIE { get; set; }
        public string DESC_DESTRITO { get; set; }
        public string DESC_CONTA_CORRENTE { get; set; }
        public Nullable<int> COD_OPERACAO_CC1 { get; set; }
        public Nullable<int> COD_OPERACAO_CC2 { get; set; }
        public string DESC_PLACA { get; set; }
        public Nullable<decimal> PERC_DESCONTO { get; set; }
        public string IND_LIBERA_BLOQUETO { get; set; }
        public Nullable<System.DateTime> DT_CONSULTA_SINTEGRA { get; set; }
        public string DESC_PROFISSAO_CONJUGE { get; set; }
        public Nullable<System.DateTime> DT_NASCIMENTO_CONJUGE { get; set; }
        public string DESC_EMPRESA_CONJUGE { get; set; }
        public Nullable<decimal> VL_SALARIO_CONJUGE { get; set; }
        public string DESC_FUNCAO { get; set; }
        public string DESC_EMPRESA { get; set; }
        public string DESC_FONE_EMPRESA { get; set; }
        public string DESC_TEMPO { get; set; }
        public string DESC_PLACA_CARRETA1 { get; set; }
        public string DESC_PLACA_CARRETA2 { get; set; }
        public string DESC_BAIRRO_COBRANCA { get; set; }
        public Nullable<decimal> VAL_SALARIO { get; set; }
        public string DESC_AGENCIA { get; set; }
        public string DESC_GARANTIAS { get; set; }
        public string NOME_AUTORIZADO1 { get; set; }
        public string NOME_AUTORIZADO2 { get; set; }
        public string NOME_AUTORIZADO3 { get; set; }
        public string DESC_CPF_AUTORIZADO1 { get; set; }
        public string DESC_CPF_AUTORIZADO2 { get; set; }
        public string DESC_CPF_AUTORIZADO3 { get; set; }
        public string DESC_GARANTIAS_OUTRAS { get; set; }
        public Nullable<short> NUM_DIA_VISITA { get; set; }
        public string DESC_FREQUENCIA_VISITA { get; set; }
        public Nullable<short> NUM_HORA_VISITA { get; set; }
        public Nullable<byte> NUM_DIA_VENCTO { get; set; }
        public string NOME_TITULAR { get; set; }
        public Nullable<System.DateTime> DT_SEPROCADO { get; set; }
        public Nullable<decimal> PERC_META { get; set; }
        public Nullable<int> COD_PRAZO_VENCIMENTO { get; set; }
        public string IND_SOJICULTOR_PARTICIPANTE { get; set; }
        public string DESC_COMPLEMENTO_SINTEGRA { get; set; }
        public string DESC_CRC { get; set; }
        public string DESC_SUFRAMA { get; set; }
        public string DESC_QUALIFICACAO { get; set; }
        public Nullable<decimal> PERC_ESPECIAL_PECA { get; set; }
        public Nullable<decimal> PERC_ESPECIAL_SERVICO { get; set; }
        public string DESC_E_MAIL_CONJUGE { get; set; }
        public string DESC_TELEFONE_CONJUGE { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public string IND_ATACADO_VAREJO { get; set; }
        public Nullable<System.DateTime> DT_ULT_ALTERACAO { get; set; }
        public Nullable<decimal> PERC_SENAR { get; set; }
        public Nullable<short> NUM_LIBERA_LIMITE { get; set; }
        public string DESC_E_MAIL1 { get; set; }
        public string COD_UF_VEICULO { get; set; }
        public string DESC_DISTRITO { get; set; }
        public Nullable<int> COD_AVALISTA { get; set; }
        public Nullable<short> IND_ISS_RETIDO { get; set; }
        public Nullable<decimal> PERC_BASE_SUBSTITUICAO { get; set; }
        public Nullable<decimal> PERC_ALIQ_SUBSTITUICAO { get; set; }
        public string DESC_LEI_SUBSTITUICAO { get; set; }
        public Nullable<short> IND_REGIME_TRIBUTARIO { get; set; }
        public Nullable<decimal> PERC_DESCONTO2 { get; set; }
        public Nullable<decimal> PERC_DEDUCAO_NFSE { get; set; }
        public string COD_QUALIFICACAO_SOCIO { get; set; }
        public Nullable<decimal> PERC_CAP_TOT { get; set; }
        public Nullable<decimal> PERC_CAP_VOT { get; set; }
        public string IND_PIS_COFINS_RETIDO { get; set; }
        public Nullable<int> COD_CADASTRO_WEB { get; set; }
        public string LOCAL_ULTIMA_ALTERACAO { get; set; }
        public string NUM_CGC_CPF_TITULAR_CONTA { get; set; }
        public Nullable<int> COD_TABELA_PRECO_CAB { get; set; }
        public string IND_CONSUMIDOR_FINAL { get; set; }
        public string IND_CONTRIBUINTE { get; set; }
        public Nullable<System.DateTime> DT_VENCIMENTO_TABELA_PRECO { get; set; }
        public string DESC_OPERADORA_CELULAR { get; set; }
        public string NUM_SEQ_CRC { get; set; }
        public Nullable<System.DateTime> DT_CRC { get; set; }
        public Nullable<decimal> PERC_ROYALTIES { get; set; }
        public short IND_TIPO_PROPRIETARIO { get; set; }
        public string DESC_RNTRC { get; set; }
        public string DESC_TAF { get; set; }
        public string DESC_NRO_REG_ESTADUAL { get; set; }
        public string IND_SINC_MAX_ROTEIRIZADOR { get; set; }
        public Nullable<int> COD_FILIAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CADASTRO_ENDERECOS> TB_CADASTRO_ENDERECOS { get; set; }
        public virtual TB_CIDADE TB_CIDADE { get; set; }
        public virtual TB_CLASS_CADASTRO TB_CLASS_CADASTRO { get; set; }
        public virtual TB_ESTADO TB_ESTADO { get; set; }
        public virtual TB_ESTADO_CIVIL TB_ESTADO_CIVIL { get; set; }
        public virtual TB_ESTADO TB_ESTADO1 { get; set; }
        public virtual TB_REGIAO TB_REGIAO { get; set; }
        public virtual TB_TIPO_CADASTRO TB_TIPO_CADASTRO { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_FILIAL> TB_FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_FILIAL> TB_FILIAL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LOTE_TIPO> TB_LOTE_TIPO { get; set; }
        public virtual TB_MOTIVO TB_MOTIVO { get; set; }
        public virtual TB_PAIS TB_PAIS { get; set; }
        public virtual TB_QUALIFICACAO_SOCIO TB_QUALIFICACAO_SOCIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROPRIEDADE> TB_PROPRIEDADE { get; set; }
        public virtual TB_RAMO TB_RAMO { get; set; }
        public virtual TB_TABELA_PRECO_CAB TB_TABELA_PRECO_CAB { get; set; }
        public virtual TB_VENDEDOR TB_VENDEDOR { get; set; }
        public virtual TB_OPERACAO TB_OPERACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PEDIDO_CAB> TB_PEDIDO_CAB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PEDIDO_CAB> TB_PEDIDO_CAB1 { get; set; }
    }
}
