//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONFIGURACAO_SKYHUB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CONFIGURACAO_SKYHUB()
        {
            this.TB_EMAIL_NOTIFICACAO = new HashSet<TB_EMAIL_NOTIFICACAO>();
        }
    
        public int COD_CONFIGURACAO_SKYHUB { get; set; }
        public int COD_FILIAL { get; set; }
        public string IND_ATIVO { get; set; }
        public string DESC_USUARIO_EMAIL { get; set; }
        public string DESC_TOKEN_INTEGRACAO { get; set; }
        public string DESC_TOKEN_ACCOUNT { get; set; }
        public Nullable<int> COD_OPERACAO { get; set; }
        public Nullable<int> COD_CLASS_CADASTRO { get; set; }
        public Nullable<int> COD_RAMO_FISICA { get; set; }
        public Nullable<int> COD_RAMO_JURIDICA { get; set; }
        public Nullable<int> COD_TIPO_CADASTRO { get; set; }
        public Nullable<int> COD_DEPARTAMENTO { get; set; }
        public Nullable<int> COD_LOTE_TIPO { get; set; }
        public string IND_TIPO_PAGAMENTO { get; set; }
        public Nullable<int> COD_VENDEDOR { get; set; }
        public Nullable<int> COD_REGIAO { get; set; }
        public string DESC_ML_CLIENT_ID { get; set; }
        public string DESC_ML_CLIENT_SECRET { get; set; }
        public string IND_ML_ATIVO { get; set; }
        public string DESC_ACCESS_TOKEN_ML { get; set; }
        public string DESC_USER_ID_ML { get; set; }
        public Nullable<System.DateTime> DT_ACCESS_TOKEN_ML { get; set; }
        public Nullable<System.DateTime> DT_ULTIMA_ATUALIZACAO_ML { get; set; }
        public string DESC_SKYHUB_TOKEN { get; set; }
        public Nullable<System.DateTime> DT_TOKEN_SKYHUB { get; set; }
        public string IMGUR_CLIENT_ID { get; set; }
        public string IMGUR_SECRET { get; set; }
        public string IMGUR_REFRESH_TOKEN { get; set; }
        public string IMGUR_ACCESS_TOKEN { get; set; }
        public Nullable<System.DateTime> IMGUR_DT_ACCESS_TOKEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_EMAIL_NOTIFICACAO> TB_EMAIL_NOTIFICACAO { get; set; }
    }
}
