//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONTA_CORRENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CONTA_CORRENTE()
        {
            this.TB_PEDIDO_CAB = new HashSet<TB_PEDIDO_CAB>();
        }
    
        public int COD_CONTA_CORRENTE { get; set; }
        public Nullable<int> COD_BANCO_AGENCIA { get; set; }
        public string NUM_CONTA_CORRENTE { get; set; }
        public Nullable<decimal> VAL_LIMITE { get; set; }
        public Nullable<System.DateTime> DT_VENC_LIMITE { get; set; }
        public Nullable<int> NUM_CHEQUE { get; set; }
        public string DESC_CONTA_CORRENTE { get; set; }
        public string NOME_RESPONSAVEL { get; set; }
        public int COD_FILIAL { get; set; }
        public string IND_FLUXO_CAIXA { get; set; }
        public string IND_CHEQUE_PRE_DATADO { get; set; }
        public Nullable<byte> VARIACAO { get; set; }
        public Nullable<byte> CARTEIRA { get; set; }
        public Nullable<byte> COMANDO { get; set; }
        public string PRIMEIRA_INSTR_COD { get; set; }
        public Nullable<byte> NR_DIAS_PROTESTO { get; set; }
        public Nullable<int> NUM_CONVENIO { get; set; }
        public Nullable<int> COD_CONVENENTE_LIDER { get; set; }
        public Nullable<int> COD_CEDENTE { get; set; }
        public string DIG_VERIFICADOR_CEDENTE { get; set; }
        public string DIG_VERIFICADOR_AGENCIA_CONTA { get; set; }
        public string COD_FORMA_CADAST_BANCO { get; set; }
        public string COD_TIPO_DOCUMENTO { get; set; }
        public string COD_IDENTIF_EMISSAO_BLOQUETO { get; set; }
        public string COD_IDENTIF_DISTRIBUICAO { get; set; }
        public string COD_IDENTIF_ACEITO { get; set; }
        public string COD_PROTESTO { get; set; }
        public string IND_SITUACAO { get; set; }
        public string DESC_TIPO_COBRANCA { get; set; }
        public string IND_CONTA_CREDITO_CLIENTE { get; set; }
        public Nullable<decimal> VAL_MULTA { get; set; }
        public string COD_IDENTIF_TIPO_BOLETO { get; set; }
    
        public virtual TB_FILIAL TB_FILIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PEDIDO_CAB> TB_PEDIDO_CAB { get; set; }
    }
}
