//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CLASS_CADASTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CLASS_CADASTRO()
        {
            this.TB_CADASTRO = new HashSet<TB_CADASTRO>();
        }
    
        public int COD_CLASS_CADASTRO { get; set; }
        public string DESC_CLASSIFICACAO { get; set; }
        public string IND_VENDA { get; set; }
        public string DESC_OBSERVACAO { get; set; }
        public Nullable<decimal> VAL_REFERENCIA { get; set; }
        public Nullable<decimal> PERC_EQUIPAMENTO { get; set; }
        public string IND_SEPROCADO_LOJA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CADASTRO> TB_CADASTRO { get; set; }
    }
}
