//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMAIL
    {
        public string DESC_EMAIL { get; set; }
        public string DESC_SENHA { get; set; }
        public string DESC_SMTP { get; set; }
        public int NUM_PORTA_SMTP { get; set; }
        public string DESC_POP3 { get; set; }
        public int NUM_PORTA_POP3 { get; set; }
        public int COD_EMAIL { get; set; }
        public string DESC_HOME_PAGE { get; set; }
        public Nullable<short> QTD_COTA { get; set; }
        public string IND_SSL { get; set; }
    }
}
