//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMAIL_NOTIFICACAO
    {
        public int COD_EMAIL_NOTIFICACAO { get; set; }
        public int COD_CONFIGURACAO_SKYHUB { get; set; }
        public string DESC_EMAIL { get; set; }
    
        public virtual TB_CONFIGURACAO_SKYHUB TB_CONFIGURACAO_SKYHUB { get; set; }
    }
}
