//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ESTADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ESTADO()
        {
            this.TB_CIDADE = new HashSet<TB_CIDADE>();
            this.TB_CADASTRO = new HashSet<TB_CADASTRO>();
            this.TB_CADASTRO1 = new HashSet<TB_CADASTRO>();
            this.TB_BANCO_AGENCIA = new HashSet<TB_BANCO_AGENCIA>();
            this.TB_VENDEDOR = new HashSet<TB_VENDEDOR>();
        }
    
        public string COD_ESTADO { get; set; }
        public string DESC_ESTADO { get; set; }
        public Nullable<decimal> PERC_TRIBUTACAO { get; set; }
        public string DESC_SIGLA_ESTADO { get; set; }
        public Nullable<decimal> PERC_FRETE { get; set; }
        public Nullable<decimal> PERC_IMPOSTO_REDUCAO { get; set; }
        public Nullable<decimal> PERC_IMPOSTO_CESTA { get; set; }
        public Nullable<decimal> PERC_BASE_SUBST { get; set; }
        public Nullable<decimal> PERC_ALIQ_SUBST { get; set; }
        public string DESC_INSCRICAO_SUBST { get; set; }
        public Nullable<byte> COD_UF_IBGE { get; set; }
        public Nullable<byte> COD_GI { get; set; }
        public Nullable<decimal> PERC_REDUCAO_ICMS_SUBST { get; set; }
        public Nullable<decimal> PERC_ALIQ_ICMS_SIMPLES { get; set; }
        public Nullable<decimal> PERC_TRIBUTADO_SN { get; set; }
        public Nullable<decimal> PERC_ALIQUOTA_DIFERENCIAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CIDADE> TB_CIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CADASTRO> TB_CADASTRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CADASTRO> TB_CADASTRO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BANCO_AGENCIA> TB_BANCO_AGENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VENDEDOR> TB_VENDEDOR { get; set; }
    }
}
