//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FILIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_FILIAL()
        {
            this.TB_SEQUENCIA = new HashSet<TB_SEQUENCIA>();
            this.TB_SERIE1 = new HashSet<TB_SERIE>();
            this.TB_ESTOQUE = new HashSet<TB_ESTOQUE>();
            this.TB_CONTA_CORRENTE = new HashSet<TB_CONTA_CORRENTE>();
            this.TB_VENDEDOR = new HashSet<TB_VENDEDOR>();
            this.TB_PEDIDO_CAB = new HashSet<TB_PEDIDO_CAB>();
            this.TB_CONFIGURACAO_SKYHUB = new HashSet<TB_CONFIGURACAO_SKYHUB>();
        }
    
        public int COD_FILIAL { get; set; }
        public string DESC_FILIAL { get; set; }
        public string DESC_CIDADE { get; set; }
        public string DESC_CEP { get; set; }
        public string DESC_ENDERECO { get; set; }
        public string NUM_CGC { get; set; }
        public string DESC_INSCRICAO { get; set; }
        public string DESC_TELEFONE { get; set; }
        public Nullable<int> NUM_NOTA_FISCAL { get; set; }
        public Nullable<int> NUM_TITULO { get; set; }
        public string IND_ESTOQUE { get; set; }
        public Nullable<int> NUM_ORCAMENTO { get; set; }
        public Nullable<int> NUM_PEDIDO { get; set; }
        public Nullable<int> NUM_RECEITA { get; set; }
        public Nullable<int> NUM_CONTRATO { get; set; }
        public Nullable<int> NUM_CPR { get; set; }
        public Nullable<int> NUM_GUIA { get; set; }
        public Nullable<int> NUM_BOLETIM { get; set; }
        public Nullable<int> NUM_CAIXA_POSTAL { get; set; }
        public Nullable<int> NUM_RECIBO { get; set; }
        public string COD_ESTADO { get; set; }
        public Nullable<System.DateTime> DT_FECHAMENTO_CONTABIL { get; set; }
        public Nullable<int> NUM_ROMANEIO { get; set; }
        public Nullable<int> NUM_PAG_RAZAO { get; set; }
        public string DESC_LPT_NOTA { get; set; }
        public string DESC_LPT_PEDIDO { get; set; }
        public string COD_SERIE { get; set; }
        public Nullable<short> NUM_ENDERECO { get; set; }
        public string DESC_COMPLEMENTO_ENDERECO { get; set; }
        public string DESC_BAIRRO { get; set; }
        public string DESC_NOME_CONTATO { get; set; }
        public string IND_PADRAO_ARQ_MAGNETICO { get; set; }
        public string IND_PADRAO_FIN_ARQ_MAGNETICO { get; set; }
        public string DESC_FAX { get; set; }
        public string DESC_E_MAIL { get; set; }
        public string IND_PORTA_BALANCA { get; set; }
        public string DESC_LPT_OS { get; set; }
        public string DESC_TIPO_BALANCA { get; set; }
        public Nullable<int> COD_CREDENCIAL_SEAB { get; set; }
        public Nullable<decimal> PERC_ISS { get; set; }
        public Nullable<int> NUM_MINISTERIO_AGRICULTURA { get; set; }
        public string IND_BLOQUEIO_VENDA_VCTO { get; set; }
        public string DESC_IMPRESSORA_FISCAL { get; set; }
        public string IND_LIBERA_PESO_ROMANEIO { get; set; }
        public string IND_ESTOQUE_NEGATIVO { get; set; }
        public string DESC_PORTA_CHRONOS { get; set; }
        public string IND_SUBSTITUICAO { get; set; }
        public Nullable<int> COD_CADASTRO { get; set; }
        public string DESC_CPF_RESPONSAVEL { get; set; }
        public string DESC_NIT { get; set; }
        public string DESC_INSCRICAO_MUNICIPAL { get; set; }
        public string DESC_SUFRAMA { get; set; }
        public Nullable<int> COD_CIDADE { get; set; }
        public Nullable<int> COD_CADASTRO_CONTABILISTA { get; set; }
        public Nullable<int> COD_CADASTRO_TECNICO { get; set; }
        public string IND_CREDITO_ICMS { get; set; }
        public string IND_IMPRIME_PEDIDO { get; set; }
        public string IND_CONTINGENCIA { get; set; }
        public string NUM_NIRE { get; set; }
        public Nullable<short> IND_AMBIENTE_NFE { get; set; }
        public string IND_TIPO_NOTA { get; set; }
        public Nullable<int> COD_CADASTRO_RESPONSAVEL { get; set; }
        public Nullable<byte> IND_SISTEMA_NFE { get; set; }
        public string DESC_LPT_CHEQUE { get; set; }
        public string DESC_LPT_CONHECIMENTO { get; set; }
        public string DESC_SERVIDOR { get; set; }
        public Nullable<byte> NUM_VIAS_DANFE { get; set; }
        public string DESC_REPOSITORIO_NFE { get; set; }
        public string IND_VIAS_DANFE { get; set; }
        public string DESC_USUARIO { get; set; }
        public string DESC_SENHA { get; set; }
        public string IND_LOGIN_NFE { get; set; }
        public string DESC_CERTIFICADO { get; set; }
        public string DESC_LOGOTIPO_DANFE { get; set; }
        public Nullable<short> IND_REGIME_TRIBUTARIO { get; set; }
        public string DESC_VERSAO_NFE { get; set; }
        public Nullable<System.DateTime> DT_CONTINGENCIA { get; set; }
        public string DESC_JUST_CONTINGENCIA { get; set; }
        public string IND_OCULTA_FONE_DANFE { get; set; }
        public string COD_ENERGIA_TENSAO { get; set; }
        public string COD_CLASSE_CONSUMO { get; set; }
        public Nullable<short> IND_TIPO_ENERGIA { get; set; }
        public string IND_TIPO_ATIVIDADE { get; set; }
        public string IND_PERFIL_SPED { get; set; }
        public string IND_ST { get; set; }
        public string IND_REGIME_ESPECIAL { get; set; }
        public Nullable<short> COD_INC_TRIB { get; set; }
        public Nullable<short> COD_APROPRIACAO_CRED { get; set; }
        public Nullable<short> COD_TIPO_CONT { get; set; }
        public Nullable<short> COD_CRITERIO_ESCRIT { get; set; }
        public string IND_IPI { get; set; }
        public string IND_PERMITE_IMP_EXP { get; set; }
        public string COD_SERIE_MODELO { get; set; }
        public Nullable<decimal> PERC_BC_NFSE { get; set; }
        public string DESC_ENVIO_EMAIL { get; set; }
        public string DESC_SENHA_EMAIL { get; set; }
        public string DESC_SMTP { get; set; }
        public Nullable<int> NUM_PORTA_SMTP { get; set; }
        public string IND_SSL { get; set; }
        public string DESC_CNAE { get; set; }
        public Nullable<short> COD_INC_TRIB_PREV { get; set; }
        public string IND_CONTINGENCIA_CTE { get; set; }
        public Nullable<short> IND_AMBIENTE_CTE { get; set; }
        public string IND_VIAS_DACTE { get; set; }
        public Nullable<byte> NUM_VIAS_DACTE { get; set; }
        public Nullable<System.DateTime> DT_CONTINGENCIA_CTE { get; set; }
        public string DESC_JUSTI_CONTINGENCIA_CTE { get; set; }
        public string DESC_VERSAO_CTE { get; set; }
        public string DESC_RNTRC { get; set; }
        public string DESC_CIOT { get; set; }
        public string DESC_LOGOTIPO_DACTE { get; set; }
        public string DESC_CERTIFICADO_CTE { get; set; }
        public string DESC_IP_TEF { get; set; }
        public string DESC_ID_TERMINAL_TEF { get; set; }
        public string DESC_ID_LOJA_TEF { get; set; }
        public Nullable<int> COD_NBS_PADRAO { get; set; }
        public string DESC_LPT_RECIBO { get; set; }
        public Nullable<short> IND_AMBIENTE_MDFE { get; set; }
        public string IND_VIAS_DAMDFE { get; set; }
        public Nullable<byte> NUM_VIAS_DAMDFE { get; set; }
        public string DESC_VERSAO_MDFE { get; set; }
        public string DESC_HASH_MD5 { get; set; }
        public Nullable<short> IND_ORIENTACAO_PAG_DANFE { get; set; }
        public Nullable<decimal> PERC_ALIQ_CRED_ICMSSN { get; set; }
        public string IND_CONSIDERA_DESC_BC { get; set; }
        public string DESC_LOGOTIPO_DAMDFE { get; set; }
        public string DESC_CERTIFICADO_MDFE { get; set; }
        public Nullable<int> COD_PIS_DCTF { get; set; }
        public Nullable<int> COD_COFINS_DCTF { get; set; }
        public string IND_CONSIDERA_IPI_BC_ICMS { get; set; }
        public string IND_CONSIDERA_IPI_BC_SUBST { get; set; }
        public Nullable<short> IND_TIPO_EMITENTE_MDFE { get; set; }
        public string IND_CONTINGENCIA_NFCE { get; set; }
        public Nullable<short> IND_AMBIENTE_NFCE { get; set; }
        public string IND_VIAS_DANFE_NFCE { get; set; }
        public Nullable<byte> NUM_VIAS_DANFE_NFCE { get; set; }
        public Nullable<System.DateTime> DT_CONTINGENCIA_NFCE { get; set; }
        public string DESC_JUST_CONTINGENCIA_NFCE { get; set; }
        public string DESC_VERSAO_NFCE { get; set; }
        public string IND_CONSUMIDOR_FINAL { get; set; }
        public Nullable<short> IND_RESP_SEGURO_PADRAO { get; set; }
        public string IND_PEDAGIO_INCLUSO { get; set; }
        public string IND_CONSIDERA_RED_BASE_SUBST { get; set; }
        public string DESC_APOLICE_SEGURO_PADRAO { get; set; }
        public Nullable<int> COD_SEGURADORA_PADRAO { get; set; }
        public string IND_MOSTRA_IE_SUBST { get; set; }
        public Nullable<System.DateTime> DT_NIRE { get; set; }
        public string DESC_CSC_NFCE { get; set; }
        public string DESC_IDENTIFICADOR_CSC_NFCE { get; set; }
        public string DESC_LOGOTIPO_DANFE_NFCE { get; set; }
        public string DESC_CERTIFICADO_NFCE { get; set; }
        public Nullable<decimal> PERC_DEDUCAO_NFSE { get; set; }
        public Nullable<byte> COD_FORMA_TRIBUTACAO { get; set; }
        public string IND_FORMA_APURACAO { get; set; }
        public string IND_DIF_FCONT { get; set; }
        public string IND_OPT_EXT_RTT { get; set; }
        public Nullable<int> COD_NATUREZA_JURIDICA { get; set; }
        public string IND_LIBERA_PESO_RENDA { get; set; }
        public string DESC_LPT_ETIQUETA { get; set; }
        public string IND_NOME_FANTASIA_DANFE { get; set; }
        public string IND_SINCRONIZA_WEB { get; set; }
        public Nullable<decimal> COD_CADASTRO_ENG_RESPONSAVEL { get; set; }
        public Nullable<System.DateTime> DT_REVISAO_ENG_RESPONSAVEL { get; set; }
        public string DESC_VERSAO_NFSE { get; set; }
        public Nullable<short> IND_AMBIENTE_NFSE { get; set; }
        public string DESC_SENHA_WS_NFSE { get; set; }
        public string DESC_EMAIL_XML_MENSAL { get; set; }
        public string IND_LOGOTIPO_DANFE_NFCE { get; set; }
        public string DESC_TAF { get; set; }
        public string DESC_NRO_REG_ESTADUAL { get; set; }
        public string IND_IMPRIME_DANFE_NFCE { get; set; }
        public string IND_IMPRIME_DANFE { get; set; }
        public string IND_IMPRIME_DACTE { get; set; }
        public string IND_IMPRIME_DAMDFE { get; set; }
        public string DESC_FANTASIA { get; set; }
        public string IND_IMPRIME_REQ_OBRA { get; set; }
        public string IND_SITUACAO { get; set; }
        public string IND_SINC_MAX_ROTEIRIZADOR { get; set; }
    
        public virtual TB_CIDADE TB_CIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SEQUENCIA> TB_SEQUENCIA { get; set; }
        public virtual TB_IND_APROPRIACAO_CREDITO TB_IND_APROPRIACAO_CREDITO { get; set; }
        public virtual TB_CLASSE_CONSUMO TB_CLASSE_CONSUMO { get; set; }
        public virtual TB_CRITERIO_ESCRIT TB_CRITERIO_ESCRIT { get; set; }
        public virtual TB_FORMA_TRIBUTACAO TB_FORMA_TRIBUTACAO { get; set; }
        public virtual TB_INCIDENCIA_TRIBUTARIA TB_INCIDENCIA_TRIBUTARIA { get; set; }
        public virtual TB_INCIDENCIA_TRIBUTARIA_PREV TB_INCIDENCIA_TRIBUTARIA_PREV { get; set; }
        public virtual TB_NATUREZA_JURIDICA TB_NATUREZA_JURIDICA { get; set; }
        public virtual TB_ENERGIA_TENSAO TB_ENERGIA_TENSAO { get; set; }
        public virtual TB_TIPO_CONTRIBUICAO TB_TIPO_CONTRIBUICAO { get; set; }
        public virtual TB_NF_ELETRONICA_CONFIG TB_NF_ELETRONICA_CONFIG { get; set; }
        public virtual TB_SERIE TB_SERIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SERIE> TB_SERIE1 { get; set; }
        public virtual TB_CADASTRO TB_CADASTRO { get; set; }
        public virtual TB_CADASTRO TB_CADASTRO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ESTOQUE> TB_ESTOQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CONTA_CORRENTE> TB_CONTA_CORRENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VENDEDOR> TB_VENDEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PEDIDO_CAB> TB_PEDIDO_CAB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CONFIGURACAO_SKYHUB> TB_CONFIGURACAO_SKYHUB { get; set; }
    }
}
