//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HISTORICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_HISTORICO()
        {
            this.TB_OPERACAO = new HashSet<TB_OPERACAO>();
        }
    
        public int COD_HISTORICO { get; set; }
        public string DESC_HISTORICO { get; set; }
        public string IND_OPERACAO { get; set; }
        public string IND_EMITE_CHEQUE { get; set; }
        public string IND_CONCILIA { get; set; }
        public Nullable<int> COD_HISTORICO_CONTABIL { get; set; }
        public string COD_CONTABIL_CRED { get; set; }
        public string COD_CONTABIL_DEB { get; set; }
        public Nullable<int> COD_HISTORICO_CAIXA { get; set; }
        public string IND_CUSTOS { get; set; }
        public Nullable<int> COD_GRUPO { get; set; }
        public Nullable<int> COD_DEPARTAMENTO { get; set; }
        public string IND_SITUACAO { get; set; }
        public Nullable<int> COD_CENTRO_CUSTO { get; set; }
        public string IND_VEICULO { get; set; }
        public string IND_LANCTO_MOV_FLUXO { get; set; }
        public string IND_ADIANTAMENTO { get; set; }
        public string IND_TIPO_CUSTO { get; set; }
        public string IND_TIPO_RECIBO { get; set; }
        public string IND_REL_CAIXA_BANCO { get; set; }
        public string NUM_PLANO_CONTA_CAIXA { get; set; }
        public string IND_DRE_POLYANA { get; set; }
    
        public virtual TB_CENTRO_CUSTO TB_CENTRO_CUSTO { get; set; }
        public virtual TB_DEPARTAMENTO TB_DEPARTAMENTO { get; set; }
        public virtual TB_GRUPO_CUSTOS TB_GRUPO_CUSTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_OPERACAO> TB_OPERACAO { get; set; }
    }
}
