//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LOTE_TIPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_LOTE_TIPO()
        {
            this.TB_ESTOQUE = new HashSet<TB_ESTOQUE>();
        }
    
        public int COD_LOTE_TIPO { get; set; }
        public string DESC_GERMINACAO { get; set; }
        public string DESC_LOTE { get; set; }
        public string DESC_PUREZA { get; set; }
        public string DESC_ATESTADO { get; set; }
        public string DESC_VALIDADE { get; set; }
        public string DESC_PENEIRA { get; set; }
        public string DESC_OBSERVACAO { get; set; }
        public string IND_IMPRIME_NF { get; set; }
        public Nullable<long> COD_PRODUTO { get; set; }
        public Nullable<System.DateTime> DT_VENCIMENTO { get; set; }
        public string IND_TIPO_PRODUCAO { get; set; }
        public string DESC_TIPO_SEMENTE { get; set; }
        public string DESC_CATEGORIA { get; set; }
        public string DESC_RENASEN { get; set; }
        public Nullable<int> COD_CADASTRO { get; set; }
        public Nullable<System.DateTime> DT_FABRICACAO { get; set; }
        public Nullable<decimal> VAL_PRECO { get; set; }
        public Nullable<decimal> NUM_PESO { get; set; }
        public string IND_SITUACAO { get; set; }
    
        public virtual TB_CADASTRO TB_CADASTRO { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ESTOQUE> TB_ESTOQUE { get; set; }
    }
}
