//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MENSAGEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_MENSAGEM()
        {
            this.TB_PEDIDO_CAB = new HashSet<TB_PEDIDO_CAB>();
        }
    
        public int COD_MENSAGEM { get; set; }
        public string DESC_MENSAGEM { get; set; }
        public string DESC_COMPLEMENTO { get; set; }
        public string DESC_COMPLEMENTO1 { get; set; }
        public string DESC_COMPLEMENTO2 { get; set; }
        public string DESC_COMPLEMENTO3 { get; set; }
        public string DESC_COMPLEMENTO4 { get; set; }
        public string DESC_COMPLEMENTO5 { get; set; }
        public string DESC_COMPLEMENTO6 { get; set; }
        public string DESC_COMPLEMENTO7 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PEDIDO_CAB> TB_PEDIDO_CAB { get; set; }
    }
}
