//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRAZO_VENCIMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PRAZO_VENCIMENTO()
        {
            this.TB_PEDIDO_CAB = new HashSet<TB_PEDIDO_CAB>();
        }
    
        public int COD_PRAZO_VENCIMENTO { get; set; }
        public string DESC_PRAZO_VENCIMENTO { get; set; }
        public byte NUM_PARCELAS { get; set; }
        public string IND_SITUACAO { get; set; }
        public Nullable<byte> NUM_DIAS_CARENCIA1 { get; set; }
        public Nullable<byte> NUM_DIAS_CARENCIA2 { get; set; }
        public Nullable<byte> NUM_DIAS_CARENCIA3 { get; set; }
        public Nullable<byte> NUM_DIAS_CARENCIA4 { get; set; }
        public Nullable<byte> NUM_DIAS_CARENCIA5 { get; set; }
        public Nullable<byte> NUM_DIAS_CARENCIA6 { get; set; }
        public Nullable<byte> NUM_DIAS_CARENCIA7 { get; set; }
        public Nullable<decimal> PERC_CARENCIA1 { get; set; }
        public Nullable<decimal> PERC_CARENCIA2 { get; set; }
        public Nullable<decimal> PERC_CARENCIA3 { get; set; }
        public Nullable<decimal> PERC_CARENCIA4 { get; set; }
        public Nullable<decimal> PERC_CARENCIA5 { get; set; }
        public Nullable<decimal> PERC_CARENCIA6 { get; set; }
        public Nullable<decimal> PERC_CARENCIA7 { get; set; }
        public Nullable<decimal> PERC_DESCONTO { get; set; }
        public string IND_ENTRADA { get; set; }
        public Nullable<byte> NUM_PRAZO_MAXIMO { get; set; }
        public string IND_TIPO_PAGTO { get; set; }
        public Nullable<decimal> VAL_MINIMO_VENDA { get; set; }
        public string IND_FORA_MES { get; set; }
        public string IND_JURO_COMPOSTO { get; set; }
        public string IND_SUBST_PRIMEIRA_PARC { get; set; }
        public Nullable<decimal> PERC_JUROS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PEDIDO_CAB> TB_PEDIDO_CAB { get; set; }
    }
}
