//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROPRIEDADE
    {
        public int COD_PROPRIEDADE { get; set; }
        public Nullable<int> COD_CADASTRO { get; set; }
        public Nullable<int> COD_TIPO_PROPRIEDADE { get; set; }
        public string DESC_PROPRIEDADE { get; set; }
        public Nullable<short> NUM_ANO { get; set; }
        public Nullable<decimal> VAL_PROPRIEDADE { get; set; }
        public Nullable<decimal> NUM_AREA { get; set; }
        public string DESC_LOCALIDADE { get; set; }
        public string DESC_OBSERVACAO { get; set; }
        public string IND_HIPOTECA { get; set; }
        public string DESC_GRAU_HIPOTECA { get; set; }
        public Nullable<decimal> VAL_HIPOTECA { get; set; }
        public string DESC_FAVORECIDO_HIPOTECA { get; set; }
        public Nullable<System.DateTime> DT_VENC_HIPOTECA { get; set; }
        public Nullable<int> COD_CIDADE { get; set; }
        public string DESC_BAIRRO { get; set; }
        public string DESC_CEP { get; set; }
        public Nullable<int> NUM_MATRICULA { get; set; }
        public string IND_TIPO_IMOVEL { get; set; }
        public Nullable<short> QT_RENDA_SAFRA { get; set; }
        public Nullable<short> QT_RENDA_SAFRINHA { get; set; }
        public Nullable<decimal> VAL_HIPOTECA2 { get; set; }
        public Nullable<decimal> VAL_HIPOTECA3 { get; set; }
        public Nullable<decimal> VAL_HIPOTECA4 { get; set; }
        public Nullable<decimal> VAL_HIPOTECA5 { get; set; }
        public Nullable<decimal> VAL_HIPOTECA6 { get; set; }
        public Nullable<System.DateTime> DT_VENC_HIPOTECA2 { get; set; }
        public Nullable<System.DateTime> DT_VENC_HIPOTECA3 { get; set; }
        public Nullable<System.DateTime> DT_VENC_HIPOTECA4 { get; set; }
        public Nullable<System.DateTime> DT_VENC_HIPOTECA5 { get; set; }
        public Nullable<System.DateTime> DT_VENC_HIPOTECA6 { get; set; }
        public string DESC_FAVORECIDO_HIPOTECA2 { get; set; }
        public string DESC_FAVORECIDO_HIPOTECA3 { get; set; }
        public string DESC_FAVORECIDO_HIPOTECA4 { get; set; }
        public string DESC_FAVORECIDO_HIPOTECA5 { get; set; }
        public string DESC_FAVORECIDO_HIPOTECA6 { get; set; }
        public string DESC_CRI { get; set; }
        public Nullable<System.DateTime> DT_VENC_CONTRATO { get; set; }
        public Nullable<int> COD_CADASTRO_PROPRIETARIO { get; set; }
    
        public virtual TB_CIDADE TB_CIDADE { get; set; }
        public virtual TB_TIPO_PROPRIEDADE TB_TIPO_PROPRIEDADE { get; set; }
    }
}
