//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PEDIDO_ITEM
    {
        public int COD_PEDIDO_ITEM { get; set; }
        public Nullable<int> COD_PEDIDO_CAB { get; set; }
        public Nullable<long> COD_PRODUTO { get; set; }
        public Nullable<int> COD_TRIBUTACAO { get; set; }
        public decimal QT_PEDIDO { get; set; }
        public decimal VAL_UNITARIO { get; set; }
        public decimal QT_ATENDIDO { get; set; }
        public decimal QT_CANCELADO { get; set; }
        public decimal PERC_DESCONTO { get; set; }
        public Nullable<int> COD_LOTE_TIPO { get; set; }
        public Nullable<decimal> PERC_COMISSAO { get; set; }
        public Nullable<int> COD_PRODUTO_AUX { get; set; }
        public Nullable<decimal> QT_EMBALAGEM { get; set; }
        public Nullable<decimal> QT_QUANTIDADE_AUX { get; set; }
        public Nullable<decimal> VAL_DESCONTO { get; set; }
        public Nullable<decimal> PERC_DESCONTO1 { get; set; }
        public Nullable<decimal> PERC_DESCONTO2 { get; set; }
        public Nullable<decimal> PERC_ACRESCIMO { get; set; }
        public Nullable<int> COD_CULTURA { get; set; }
        public string COD_ORIGEM { get; set; }
        public Nullable<int> COD_MOTIVO { get; set; }
        public string NUM_FABRICANTE { get; set; }
        public Nullable<int> COD_MARCA { get; set; }
        public Nullable<decimal> VAL_ICMS_SUBST { get; set; }
        public Nullable<decimal> VAL_IPI { get; set; }
        public Nullable<decimal> PERC_COMISSAO_PREPOSTO { get; set; }
        public Nullable<short> COD_CFOP { get; set; }
        public Nullable<int> COD_PEDIDO_ITEM_WEB { get; set; }
        public string LOCAL_ULTIMA_ALTERACAO { get; set; }
        public string DESC_OBS_ITEM { get; set; }
        public Nullable<int> COD_TABELA_PRECO_CAB { get; set; }
        public Nullable<decimal> VAL_DESCONTO_VISUAL { get; set; }
        public Nullable<int> COD_COR { get; set; }
        public Nullable<decimal> VAL_COMPRIMENTO { get; set; }
        public Nullable<decimal> VAL_DIAMETRO { get; set; }
        public string IND_SINC_MAX_ROTEIRIZADOR { get; set; }
    
        public virtual TB_MARCA TB_MARCA { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO { get; set; }
        public virtual TB_TABELA_PRECO_CAB TB_TABELA_PRECO_CAB { get; set; }
        public virtual TB_PEDIDO_CAB TB_PEDIDO_CAB { get; set; }
    }
}
