//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUTO_IMAGEM_SKYHUB
    {
        public long COD_PRODUTO_IMAGEM_SKYHUB { get; set; }
        public long COD_PRODUTO_SKYHUB { get; set; }
        public string DESC_IMAGEM { get; set; }
        public string IND_ATIVO { get; set; }
    
        public virtual TB_PRODUTO_SKYHUB TB_PRODUTO_SKYHUB { get; set; }
    }
}
