//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUTO_SKYHUB_URL
    {
        public int COD_PRODUTO_SKYHUB_URL { get; set; }
        public int COD_PRODUTO_SKYHUB { get; set; }
        public int COD_FILIAL { get; set; }
        public string URL_SUBMARINO { get; set; }
        public string URL_SHOPTIME { get; set; }
        public string URL_AMERICANAS { get; set; }
        public string URL_MLIVRE { get; set; }
    
        public virtual TB_PRODUTO_SKYHUB TB_PRODUTO_SKYHUB { get; set; }
    }
}
