//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PEDIDO_CAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PEDIDO_CAB()
        {
            this.TB_PEDIDO_ITEM = new HashSet<TB_PEDIDO_ITEM>();
        }
    
        public int COD_PEDIDO_CAB { get; set; }
        public Nullable<int> COD_FILIAL { get; set; }
        public int COD_OPERACAO { get; set; }
        public Nullable<int> COD_VENDEDOR { get; set; }
        public Nullable<int> COD_CADASTRO { get; set; }
        public Nullable<int> NUM_PEDIDO { get; set; }
        public System.DateTime DT_EMISSAO { get; set; }
        public Nullable<decimal> VAL_DESCONTO { get; set; }
        public Nullable<System.DateTime> DT_ENTREGA { get; set; }
        public Nullable<System.DateTime> DT_FATURAMENTO { get; set; }
        public Nullable<System.DateTime> DT_SISTEMA { get; set; }
        public string DESC_OBSERVACAO { get; set; }
        public string DESC_COMPLEMENTO_OBS { get; set; }
        public Nullable<decimal> PERC_COMISSAO { get; set; }
        public string DESC_COMPLEMENTO_OBS2 { get; set; }
        public Nullable<System.DateTime> DT_VENCIMENTO { get; set; }
        public string IND_TIPO_PAGAMENTO { get; set; }
        public Nullable<long> COD_PRODUTO { get; set; }
        public Nullable<decimal> QT_QUANTIDADE { get; set; }
        public Nullable<int> COD_USUARIO { get; set; }
        public Nullable<byte> NR_DIAS_CHEQUE { get; set; }
        public Nullable<byte> NR_DIAS_CHEQUE1 { get; set; }
        public Nullable<byte> NR_DIAS_CHEQUE2 { get; set; }
        public Nullable<byte> NR_DIAS_CHEQUE3 { get; set; }
        public Nullable<int> COD_PRAZO_VENCIMENTO { get; set; }
        public string IND_TIPO_FRETE { get; set; }
        public Nullable<int> COD_CULTURA { get; set; }
        public Nullable<System.DateTime> DT_ENTREGA_PRORROGADA { get; set; }
        public Nullable<byte> NR_DIAS_CHEQUE4 { get; set; }
        public Nullable<int> COD_MENSAGEM { get; set; }
        public Nullable<int> COD_DEPARTAMENTO { get; set; }
        public Nullable<int> COD_BANCO_AGENCIA { get; set; }
        public string IND_SITUACAO { get; set; }
        public string IND_ESTOQUE { get; set; }
        public string IND_EMBARQUE { get; set; }
        public Nullable<int> NUM_PALM { get; set; }
        public Nullable<int> COD_CONTA_CORRENTE { get; set; }
        public string IND_PRECO_TABELA { get; set; }
        public Nullable<decimal> VAL_IMPOSTO { get; set; }
        public string IND_LIBERADO { get; set; }
        public Nullable<decimal> PERC_SUB { get; set; }
        public Nullable<int> COD_USUARIO_LIB_CAD { get; set; }
        public Nullable<int> COD_USUARIO_LIB_FIN { get; set; }
        public Nullable<int> COD_USUARIO_LIB_COM { get; set; }
        public Nullable<decimal> PERC_LUCRO { get; set; }
        public Nullable<decimal> PERC_ISSQN { get; set; }
        public Nullable<decimal> VAL_TOTAL { get; set; }
        public Nullable<decimal> VAL_ADIANTAMENTO { get; set; }
        public string COD_SERIE { get; set; }
        public string DESC_VEICULO { get; set; }
        public string DESC_TECIDO { get; set; }
        public string DESC_FORMA_PAGAMENTO { get; set; }
        public Nullable<decimal> VAL_ENTRADA { get; set; }
        public Nullable<int> COD_CADASTRO_TRANSPORTADORA { get; set; }
        public string DESC_CHASSI { get; set; }
        public string NUM_ORDEM_COMPRA { get; set; }
        public string DESC_SAFRA { get; set; }
        public Nullable<int> COD_VENDEDOR_PREPOSTO { get; set; }
        public Nullable<System.DateTime> DT_USUARIO { get; set; }
        public Nullable<int> COD_PEDIDO_WEB { get; set; }
        public string LOCAL_ULTIMA_ALTERACAO { get; set; }
        public Nullable<bool> STEP_PEDIDO_WEB { get; set; }
        public Nullable<int> COD_OBRA { get; set; }
        public string IND_CONSUMIDOR_FINAL { get; set; }
        public Nullable<int> COD_VEICULO { get; set; }
        public string STEP_SINCRONIZACAO { get; set; }
        public Nullable<decimal> VAL_DESPESAS { get; set; }
        public string IND_SINC_MAX_ROTEIRIZADOR { get; set; }
        public string DESC_SITUACAO_SKYHUB { get; set; }
        public string COD_PEDIDO_MARKETPLACE { get; set; }
    
        public virtual TB_CADASTRO TB_CADASTRO { get; set; }
        public virtual TB_CADASTRO TB_CADASTRO1 { get; set; }
        public virtual TB_VENDEDOR TB_VENDEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PEDIDO_ITEM> TB_PEDIDO_ITEM { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO { get; set; }
    }
}
