//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SEQUENCIA
    {
        public string NOME_SEQUENCIA { get; set; }
        public int COD_FILIAL { get; set; }
        public int VAL_SEQUENCIA { get; set; }
    }
}
