//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SERIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_SERIE()
        {
            this.TB_FILIAL = new HashSet<TB_FILIAL>();
            this.TB_USUARIO = new HashSet<TB_USUARIO>();
            this.TB_USUARIO1 = new HashSet<TB_USUARIO>();
        }
    
        public string COD_SERIE { get; set; }
        public Nullable<int> NUM_SERIE { get; set; }
        public int COD_FILIAL { get; set; }
        public string COD_SERIE_MODELO { get; set; }
        public Nullable<short> NUM_SERIE_FISCAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_FILIAL> TB_FILIAL { get; set; }
        public virtual TB_FILIAL TB_FILIAL1 { get; set; }
        public virtual TB_SERIE_MODELO TB_SERIE_MODELO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_USUARIO> TB_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_USUARIO> TB_USUARIO1 { get; set; }
    }
}
