//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SINCRONIZACAO_SKYHUB
    {
        public string TIPO_ACAO { get; set; }
        public string IND_SINCRONIZADO { get; set; }
        public long COD_PRODUTO { get; set; }
        public Nullable<System.DateTime> DT_REGISTRO { get; set; }
        public Nullable<System.DateTime> DT_SINCRONIZACAO { get; set; }
        public int COD_SINCRONIZACAO_SKYHUB { get; set; }
        public string IND_SINCRONIZADO_ML { get; set; }
        public Nullable<System.DateTime> DT_SINCRONIZACAO_ML { get; set; }
    
        public virtual TB_PRODUTO TB_PRODUTO { get; set; }
    }
}
