//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TIPO_PROPRIEDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_TIPO_PROPRIEDADE()
        {
            this.TB_PROPRIEDADE = new HashSet<TB_PROPRIEDADE>();
        }
    
        public int COD_TIPO_PROPRIEDADE { get; set; }
        public string DESC_TIPO_PROPRIEDADE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROPRIEDADE> TB_PROPRIEDADE { get; set; }
    }
}
