//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TABELA_PRECO_ITEM
    {
        public int COD_TABELA_PRECO_ITEM { get; set; }
        public int COD_TABELA_PRECO_CAB { get; set; }
        public long COD_PRODUTO { get; set; }
        public decimal VAL_PRECO { get; set; }
    
        public virtual TB_PRODUTO TB_PRODUTO { get; set; }
        public virtual TB_TABELA_PRECO_CAB TB_TABELA_PRECO_CAB { get; set; }
    }
}
