//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TABELA_PRECO_CAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_TABELA_PRECO_CAB()
        {
            this.TB_CADASTRO = new HashSet<TB_CADASTRO>();
            this.TB_TABELA_PRECO_ITEM = new HashSet<TB_TABELA_PRECO_ITEM>();
            this.TB_PEDIDO_ITEM = new HashSet<TB_PEDIDO_ITEM>();
        }
    
        public int COD_TABELA_PRECO_CAB { get; set; }
        public string DESC_TABELA_PRECO { get; set; }
        public string IND_SITUACAO { get; set; }
        public string IND_BLOQUEIA_DESCONTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CADASTRO> TB_CADASTRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TABELA_PRECO_ITEM> TB_TABELA_PRECO_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PEDIDO_ITEM> TB_PEDIDO_ITEM { get; set; }
    }
}
