//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TRIBUTACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_TRIBUTACAO()
        {
            this.TB_PRODUTO = new HashSet<TB_PRODUTO>();
        }
    
        public int COD_TRIBUTACAO { get; set; }
        public string DESC_TRIBUTACAO { get; set; }
        public decimal PERC_TRIBUTADO { get; set; }
        public decimal PERC_ALIQUOTA { get; set; }
        public string NUM_CLASSIFICACAO { get; set; }
        public string COD_TRIB_IMP_FISCAL { get; set; }
        public string DESC_SITUACAO_TRIB { get; set; }
        public string DESC_OBSERVACAO { get; set; }
        public string IND_BASE_REDUZIDA { get; set; }
        public Nullable<decimal> PERC_TRIBUTADO_NOTA { get; set; }
        public string DESC_CSOSN { get; set; }
        public string NUM_INDICE_TRIB_ECF { get; set; }
        public string DESC_HASH_MD5 { get; set; }
        public Nullable<decimal> PERC_DIFERIMENTO { get; set; }
        public string DESC_SITUACAO_TRIB_NC { get; set; }
        public string DESC_CSOSN_NC { get; set; }
        public string DESC_OBSERVACAO_NC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PRODUTO> TB_PRODUTO { get; set; }
    }
}
