//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cemapa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_USUARIO()
        {
            this.TB_CADASTRO = new HashSet<TB_CADASTRO>();
        }
    
        public int COD_USUARIO { get; set; }
        public string DESC_SENHA { get; set; }
        public System.DateTime DT_ULTIMA_ALTERACAO { get; set; }
        public byte NUM_DIAS_ALTERACAO { get; set; }
        public string IND_PRIVILEGIO { get; set; }
        public byte COD_DEPARTAMENTO { get; set; }
        public byte COD_FILIAL { get; set; }
        public string NOME { get; set; }
        public string COD_SERIE_PADRAO { get; set; }
        public Nullable<int> COD_CLIENTE_PADRAO { get; set; }
        public Nullable<int> COD_OPERACAO_PADRAO { get; set; }
        public Nullable<int> COD_VENDEDOR_PADRAO { get; set; }
        public string COD_SERIE_PRAZO { get; set; }
        public string COD_SERIE_CC { get; set; }
        public string COD_SERIE_CARTAO { get; set; }
        public string IND_CONTABIL_PRIVILEGIO { get; set; }
        public string DESC_TIPO_FUNCIONARIO { get; set; }
        public Nullable<decimal> PERC_DESCONTO_MAXIMO { get; set; }
        public Nullable<int> COD_PARCERIA { get; set; }
        public Nullable<int> COD_FINALIDADE { get; set; }
        public string DESC_SENHA_NFE { get; set; }
        public string DESC_IMPRESSORA_DANFE { get; set; }
        public string DESC_LOGIN_LFAX { get; set; }
        public string DESC_SENHA_LFAX { get; set; }
        public string COD_SERIE_MODELO_PADRAO { get; set; }
        public string COD_SERIE_MODELO_PRAZO { get; set; }
        public string DESC_IMPRESSORA_DACTE { get; set; }
        public string COD_SERIE_CTE { get; set; }
        public string COD_SERIE_MODELO_CTE { get; set; }
        public Nullable<int> COD_OPERACAO_CTE { get; set; }
        public Nullable<int> COD_TRIBUTACAO_PADRAO_CTE { get; set; }
        public string DESC_IMPRESSORA_DANFE_NFCE { get; set; }
        public Nullable<int> COD_FINALIDADE_PAGAR { get; set; }
        public string DESC_IMPRESSORA_VALE_PRODUTO { get; set; }
        public string DESC_IMPRESSORA_ZEBRA_EPL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CADASTRO> TB_CADASTRO { get; set; }
    }
}
